spring:
  cloud:
    config:
      uri:
      - http://localhost:8888         
        
         
  application:
    name: employee-service
server:
  port: 8802     
          
        
         